### ISSUE TITLE
create seed data

### ISSUE THREAD

**Issue by matthewaustinbell** [matthewaustinbell/Capstone-SetListMaker#11]

**Comment by matthewaustinbell** [comment]
### User Story
As a developer, in order to not have to wait, I would need some seed data

### AC
Given a developer navigated to the repo
Then they should see 2 files in App.js called songs.js and setlists.js, each with multiple key value pairs

### Dev Notes

- In App.js, create a 2 files called songs.js, setlists.js
- Paste the seed data provided below within each js file

**Comment by michaelclark2** [comment]
I would also put what your data will look like,
What does a song object look like? 
What does a setlist object look like?  
I would reference your ERD for those object shapes
