### ISSUE TITLE
add base home and auth components

### ISSUE THREAD

**Issue by matthewaustinbell** [matthewaustinbell/Capstone-SetListMaker#14]

**Comment by matthewaustinbell** [comment]
if not already created, make App.js file
import `import Auth from '../components/Auth/Auth';
import `import Home from '../components/Home/Home';
delete the button tag and repleace with  `<Auth /> and `<Home /> in the dive with a className assigned to "App"

in Auth.js file import
`import React from 'react';
and import Auth.scss
`import './Auth.scss';

create a class Auth that extends React.Component 
`class Auth extends React.Component {
make a render and return
inside the return create a div with the classname "Auth"
`<div className="Auth">
inside this div create an Auth H1 
`<h1>Auth</h1>
export Auth with 
`export default Auth; 

add display block to Auth scss file 
`.Auth {
  display: block;
}

**Comment by michaelclark2** [comment]
This ticket says you have three columns of cards, but the title and dev notes only have two components.  you should list out all the components you plan on making and where they are going to live.
What is in the home component?  What is in the auth component?

**Comment by matthewaustinbell** [comment]
thank you. I was ahead of myslef on this ticket. This was just meant to display auth in a header when logged out and home in a head when logged in
