### ISSUE TITLE
wireframe

### ISSUE THREAD

**Issue by matthewaustinbell** [matthewaustinbell/Capstone-SetListMaker#22]

**Comment by matthewaustinbell** [comment]
<img width="554" alt="Screen Shot 2019-07-13 at 9 10 42 AM" src="https://user-images.githubusercontent.com/47642477/61483523-90a2fa80-a962-11e9-8480-74cfd1b5b139.png">

**Comment by michaelclark2** [comment]
what is your auth page going to look like? 
where is your navbar?
You mention there are delete buttons on the left column of songs, but i dont see them on the wireframes
I think it would be in your best interest if you went through each ticket, and made a mockup based on each ticket and put the mockup as a comment for each ticket
