### ISSUE TITLE
Create SetList Component

### ISSUE THREAD

**Issue by matthewaustinbell** [matthewaustinbell/Capstone-SetListMaker#9]

**Comment by matthewaustinbell** [comment]
User Story
As a user, I should see a dog card displayed on the page.

AC
When I navigate to the site
Then I should see a dog card display on the page.

Dev Notes

**Comment by michaelclark2** [comment]
This ticket should only be about how to create a new setlist
What does the form for entering a new setlist look like?  is it simply a button press?
